apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-aaq2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-aaq2
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-aaq2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-aaq2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-aaq2
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bizy-tenant/rhtap-demo-app/hacbs-test-project-aaq2@sha256:b99b79cffedb737cd363e6aed5d9dc345062773cf201aace27d396d066e699f4
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
